### ISSUE TITLE
improve intro explanation

### ISSUE THREAD

**Issue by ungoldman** [ungoldman/style.css#37]
Some of the feedback I've gotten about this module is that it's not totally clear what it's for from the explanation at the top of the readme. Clarifying the purpose of the module will help visitors more easily understand why they might want to use it.

Suggestions for intro text / about / features very welcome 😁 

cc @bcomnes @laduke

**Comment by laduke** [comment]
I don't know! I think the part about it mentioning 'markdown' threw me off at first. I liked what you said about making a page look nice with zero effort.

**Comment by ungoldman** [comment]
Improved! Thanks for feedback 👍
