### ISSUE TITLE
font stacks

### ISSUE THREAD

**Issue by nikolaswise** [ungoldman/style.css#9]
This is Mrmrs suggested system stack

```
font-family: -apple-system, 'avenir next', avenir, roboto, noto, 'helvetica neue', helvetica, ubuntu, 'franklin gothic medium', 'century gothic', sans-serif;
```

This is a strong set of monospace

```
font-family: "Courier New", Courier, "Nimbus Mono L", monospace;
```

**Comment by ungoldman** [comment]
I've got the following for code fonts:

```
Consolas,
'Liberation Mono',
Menlo,
Courier,
monospace
```

@paulcpederson you seemed to know the system fonts for code off the top of your head, I think @nikolaswise and I are both off by one or two in this thread.

**Comment by paulcpederson** [comment]
I have been using `Menlo, Monaco, Consolas, "Courier New", monospace`.

Visual Studio Uses:

```
Monaco,
Menlo,
Consolas,
"Droid Sans Mono",
"Inconsolata",
"Courier New",
monospace
```

Atom defaults to:

```
Menlo, // OS X
Consolas, // Windows
DejaVu Sans Mono // Some flavors of Linux
```

Sublime Text defaults to:

```
Menlo,
Consolas,
Monospace // linux?
```

**Comment by ungoldman** [comment]
Using the following list based on @paulcpederson's feedback and some extra digging.

```
menlo, // os x
inconsolata, consolas, // windows
'dejavu sans mono', 'liberation mono', 'ubuntu mono', // linux
'droid sans mono', // android
monaco, 'courier new', // older systems
monospace // fallback
```

**Comment by ungoldman** [comment]
would be good to have a complete serif stack to rival sans and the above in terms of coverage. also talked with nik tonight and leaning towards serif as system sans does feel a bit bland after a while.

**Comment by nikolaswise** [comment]
BOO

**Comment by ungoldman** [comment]
👻

**Comment by ungoldman** [comment]
I HAVE FOUND THE SERIF STACK

```scss
charter, constantia,
'lucida bright', lucidabright, 'lucida serif', lucida,
'dejavu serif', 'bitstream vera serif', 'liberation serif',
georgia, serif;
```

Adapted from the Georgia stack here: https://css-tricks.com/snippets/css/font-stacks/

In use on my site as of last night: http://ungoldman.com

I think it looks pretty, pretty, pretty good.

![](https://media.giphy.com/media/bWeR8tA1QV4cM/giphy.gif)

@nikolaswise @paulcpederson thoughts, opinions?

**Comment by ungoldman** [comment]
Calling this done for now. Would be nice to find appropriate firefox and android serif fonts one day.
